name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true
          
    - name: Install dependecies
      shell: bash
      run: |
        sudo apt update
        sudo apt install make git zlib1g-dev libssl-dev gperf -y
        
    - name: Build
      run: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=Release  ..
            cmake --build . --target install
            
    - name: ls
      run: |
        ls ${{ github.workspace }}/build
